defaults:
  - _self_
hydra:
  run:  
    dir: ${logdir}

name: gym_walker_dsrl_stride_v3_${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
logdir: ${log_dir}/gym-dsrl/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ./dppo/log/gym-pretrain/walker2d-medium-v2_pre_diffusion_mlp_ta4_td20/2024-06-12_23-06-12/checkpoint/state_3000.pt
normalization_path: ./dppo/log/gym/${env_name}/normalization.npz
dppo_path: ./dppo

algorithm: dsrl_na # options are: dsrl_na, dsrl_sac

seed: 1
device: cuda:0
use_wandb: True
env_name: walker2d-medium-v2
log_dir: ./logs
obs_dim: 17
action_dim: 6
cond_steps: 1
act_steps: 4
load_offline_data: False
deterministic_eval: False 

# Inference helpers
model_path: ""
resume_path: "" # Start from scratch to avoid old bad habits
record_episodes: 10
save_first_last: 2
eval_episodes: 10
record_video: false
video_dir: videos_inference
video_episodes: 2
video_fps: 30

traits:
  enabled: true
  resample_on_reset: true
  mask_mode: all_on
  base_reward_fn: healthy_reward
  # No schedule, train everything at once
  schedule:
    min_steps: 40000
    max_steps: 100000
    patience: 3
    min_delta: 0.0
    phases:
      - mask: [1, 1, 1, 1] 
  logging:
    enabled: true
    auto_plots: true
    sweep_points: 5
    sweep_max_points: 25
    sweep_episodes: 2
    sweep_interval: 5
    sweep_deterministic: true
    cross_mask_eval: true
    cross_mask_episodes: 2
    cross_mask_deterministic: true
  defs:
    - name: stride_td
      value_min: 1.0
      value_max: 1.0
      lambda: 550.0 # High weight for touchdown stride
    - name: reach_td
      value_min: 1.0
      value_max: 1.0
      lambda: 50.0 # Reward foot reaching ahead of body
    - name: landing_sep_max
      value_min: 1.0
      value_max: 1.0
      lambda: 50.0 # High weight for landing far from other foot
    - name: flight_penalty
      value_min: 1.0
      value_max: 1.0
      lambda: 1000.0 # MASSIVE penalty for leaping

trait_values: null
trait_mask: [1, 1, 1, 1]

eval_interval: 4000
num_evals: 200
save_model_interval: 500
save_replay_buffer: False

env:
  n_envs:  4
  n_eval_envs: 25
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 0
  reward_offset: 0
  wrappers:
    mujoco_dppo_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  project: dsrl
  run: ${now:%H-%M-%S}_${name}
  group: gym_walker_stride_v3

train:
  tau: 0.005 # Target update rate
  actor_lr: 3e-4
  batch_size: 256
  train_freq: 2 # Update model after this many environment steps
  utd: 20 # Number of gradient steps to take per update
  noise_critic_grad_steps: 10 # Number of gradient steps to take per update when fitting noise critic 
  use_layer_norm: True
  layer_size: 2048 # Layer size for actor and critic
  num_layers: 3 # Number of layers for actor and critic
  discount: 0.99
  ent_coef: -1
  target_ent: 0.0
  init_rollout_steps: 2001 # Number of rollout steps of standard diffusion policy to collect for replay buffer before training starts
  action_magnitude: 2.5 # Maximum action magnitude in noise action space
  n_critics: 2 # Number of critic Q networks
  critic_backup_combine_type: min

model:
  _target_: model.diffusion.diffusion_eval.DiffusionEval
  use_ddim: True
  ddim_steps: 5
  ft_denoising_steps: 0
  predict_epsilon: True
  denoised_clip_value: 1.0
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [512, 512, 512]
    activation_type: ReLU
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${act_steps}
    action_dim: ${action_dim}
  horizon_steps: ${act_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: 20
  device: ${device}
  controllable_noise: True

